### PR TITLE
Frame rates as list and added a new frame rate (48)

### PR DESCRIPTION
**Pull request by Synkied**
Hi CrystalComputerCorp,

First of all, thanks for this awesome module.
We're using it in on of our apps.

We wanted to add a new frame rate to the list of 'available' frame rates.
As a result, I edited your code and set framerates as a list.

What do you think of this PR? is it relevant?

### CODE REVIEW

**Comment by m1tk4** [comment]
It's a great suggestion. Before accepting the PR, let me try to figure out why it decreased coverage so much (see above).

**Comment by Synkied** [comment]
Hey !
Did you have the time to check why the coverage decreased that much ? :octocat: 

I don't see any reason for it, maybe try to run it again ? :)

**Comment by m1tk4** [comment]
It looks like one of the first tests fails and no other execute - this is just based on the coveralls web report, I haven't run them locally.

Do you mind running npm test on your workspace? (See README for the modules necessary)

**Comment by m1tk4** [comment]
@Synkied we're going to add framerates as numerator/denominator in 1.3. Thanks for the idea.

**Pull request closed without merging**
