### PR TITLE
Enabling use of 23.976 framerate

### PR DESCRIPTION
**Pull request by funkelodeon**

### CODE REVIEW

**Comment by m1tk4** [comment]
Thank you!

**Comment by gabrielboliveira** [comment]
@m1tk4 Could you tag this version and publish to npm? I had to point to the master branch directly because I was facing this issue as well. Thanks

**Comment by m1tk4** [comment]
@gabrielboliveira - published as 1.2.1, apologies.

**Comment by gabrielboliveira** [comment]
@m1tk4 thanks! no apologies needed 😄

**Pull request merged**
